apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

patches:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: application-configmap
  files:
  - configmap/application.properties

secretGenerator:
- name: application-secret
  files:
  - secret/secret.txt


