apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomize-test
  name: kustomize-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kustomize-test
  type: ClusterIP
status:
  loadBalancer: {}